version: "3.9"

services:

  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      INIT_MEMORY: "512M"
      MAX_MEMORY: "4G"
      ENABLE_AUTOPAUSE: "true"
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft:/data
    restart: unless-stopped